<a href="https://colab.research.google.com/github/shadw245/real-estate-star-schema/blob/main/notebooks/Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/STS/realtor-data.zip.csv')

In [ ]:
df.head()

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,103378.0,for_sale,105000.0,3.0,2.0,0.12,1962661.0,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,52707.0,for_sale,80000.0,4.0,2.0,0.08,1902874.0,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,103379.0,for_sale,67000.0,2.0,1.0,0.15,1404990.0,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,31239.0,for_sale,145000.0,4.0,2.0,0.10,1947675.0,Ponce,Puerto Rico,731.0,1800.0,NaN
4,34632.0,for_sale,65000.0,6.0,2.0,0.05,331151.0,Mayaguez,Puerto Rico,680.0,NaN,NaN

In [ ]:
df.shape

(2226382, 12)

In [ ]:
df.dtypes

brokered_by       float64
status             object
price             float64
bed               float64
bath              float64
acre_lot          float64
street            float64
city               object
state              object
zip_code          float64
house_size        float64
prev_sold_date     object
dtype: object

In [ ]:
df.isnull().sum()

brokered_by         4533
status                 0
price               1541
bed               481317
bath              511771
acre_lot          325589
street             10866
city                1407
state                  8
zip_code             299
house_size        568484
prev_sold_date    734297
dtype: int64

In [ ]:
df=df.drop(columns=['prev_sold_date'])

In [ ]:

df = df.dropna(subset=[
    'price',
    'city',
    'state',
    'zip_code',
    'street',
    'brokered_by'
])

In [ ]:
df['bed'] = df['bed'].fillna(df['bed'].median())

In [ ]:
df['bath'] = df['bath'].fillna(df['bath'].median())

In [ ]:
print(df['house_size'].describe())
print(df['acre_lot'].describe())

count    1.647174e+06
mean     2.713776e+03
std      8.107660e+05
min      4.000000e+00
25%      1.300000e+03
50%      1.760000e+03
75%      2.414000e+03
max      1.040400e+09
Name: house_size, dtype: float64
count    1.886350e+06
mean     1.497292e+01
std      7.630618e+02
min      0.000000e+00
25%      1.500000e-01
50%      2.600000e-01
75%      9.800000e-01
max      1.000000e+05
Name: acre_lot, dtype: float64

In [ ]:
df['house_size'] = df['house_size'].fillna(df['house_size'].median())

In [ ]:
df['acre_lot'] = df['acre_lot'].fillna(df['acre_lot'].median())

In [ ]:
df.isnull().sum()

brokered_by    0
status         0
price          0
bed            0
bath           0
acre_lot       0
street         0
city           0
state          0
zip_code       0
house_size     0
dtype: int64

In [ ]:
df.shape

(2207981, 11)

In [ ]:
#check and remove duplicates
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")

Duplicate rows: 728

In [ ]:
df = df.drop_duplicates()

In [ ]:
df['price'] = df['price'].astype(int)
df['house_size'] = df['house_size'].astype(int)
df['bed'] = df['bed'].astype(int)
df['bath'] = df['bath'].astype(int)
df['zip_code'] = df['zip_code'].astype(int)
df['brokered_by']=df['brokered_by'].astype(int)

print("Data types after conversion:")
display(df[['price', 'house_size', 'bed', 'bath', 'zip_code','brokered_by']].dtypes)

Data types after conversion:

price          int64
house_size     int64
bed            int64
bath           int64
zip_code       int64
brokered_by    int64
dtype: object

In [ ]:

print("Price value counts:")
display(df['price'].value_counts())
print("\nBed value counts:")
display(df['bed'].value_counts())
print("\nBath value counts:")
display(df['bath'].value_counts())
print("\nAcre_lot value counts:")
display(df['acre_lot'].value_counts())
print("\nHouse_size value counts:")
display(df['house_size'].value_counts())

Price value counts:

price
350000    15320
250000    15123
325000    13963
225000    13860
450000    13110
          ...
453345        1
867294        1
684884        1
633830        1
745850        1
Name: count, Length: 101527, dtype: int64

Bed value counts:

bed
3      1222878
4       437962
2       308815
5       119901
1        64332
        ...
222          1
148          1
84           1
114          1
120          1
Name: count, Length: 99, dtype: int64

Bath value counts:

bath
2      1244597
3       469509
1       258155
4       156490
5        45294
        ...
212          1
88           1
830          1
175          1
55           1
Name: count, Length: 86, dtype: int64

Acre_lot value counts:

acre_lot
0.26      347983
0.17       65776
0.14       64924
0.16       55548
0.23       55082
           ...
155.54         1
185.66         1
176.59         1
402.37         1
561.15         1
Name: count, Length: 15841, dtype: int64

House_size value counts:

house_size
1760     562107
1200       8862
1500       6274
1800       6219
1400       6068
          ...
10512         1
15308         1
9045          1
17980         1
14463         1
Name: count, Length: 12018, dtype: int64

In [ ]:
for col in ['price', 'bed', 'bath', 'acre_lot', 'house_size']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

print(f"DataFrame shape after outlier removal: {df.shape}")

DataFrame shape after outlier removal: (1513571, 11)

In [ ]:
print("Price value counts:")
display(df['price'].value_counts())
print("\nBed value counts:")
display(df['bed'].value_counts())
print("\nBath value counts:")
display(df['bath'].value_counts())
print("\nAcre_lot value counts:")
display(df['acre_lot'].value_counts())
print("\nHouse_size value counts:")
display(df['house_size'].value_counts())

Price value counts:

price
350000    11217
250000    10905
325000    10756
225000    10352
275000     9896
          ...
159711        1
304470        1
13875         1
409913        1
516100        1
Name: count, Length: 70744, dtype: int64

Bed value counts:

bed
3    893446
4    303517
2    270563
5     46045
Name: count, dtype: int64

Bath value counts:

bath
2    918184
3    349895
1    184954
4     60538
Name: count, dtype: int64

Acre_lot value counts:

acre_lot
0.26    265507
0.17     57344
0.14     56320
0.23     48491
0.16     48434
         ...
1.29       950
1.33       912
1.32       911
1.34       835
1.31       818
Name: count, Length: 135, dtype: int64

House_size value counts:

house_size
1760    323421
1200      7704
1500      5276
1400      5192
1800      4998
         ...
478          3
563          3
452          3
573          3
419          3
Name: count, Length: 2620, dtype: int64

In [ ]:
print("\nHouse_size value counts:")
display(df['brokered_by'].value_counts())

House_size value counts:

brokered_by
22611    30797
53016    15416
16829    13231
30807     6707
57595     5541
         ...
49240        1
85481        1
74811        1
68831        1
25499        1
Name: count, Length: 94647, dtype: int64

In [ ]:
#save in a csv file

df.to_csv('/content/drive/MyDrive/STS/real_cleaned.csv', index=False)